AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  EcrRepository: 
    Type: "AWS::ECR::Repository"
    Properties: 
      RepositoryName: "defi-apps-defidirect"
      LifecyclePolicy:
        LifecyclePolicyText: > 
          {
              "rules": [
                  {
                      "rulePriority": 1,
                      "description": "Keep last 20 'prod' images",
                      "selection": {
                          "tagStatus": "tagged",
                          "tagPrefixList": ["prod"],
                          "countType": "imageCountMoreThan",
                          "countNumber": 20
                      },
                      "action": {
                          "type": "expire"
                      }
                  },
                  {
                      "rulePriority": 2,
                      "description": "Keep last 20 `qa` images",
                      "selection": {
                          "tagStatus": "tagged",
                          "tagPrefixList": ["qa"],
                          "countType": "imageCountMoreThan",
                          "countNumber": 20
                      },
                      "action": {
                          "type": "expire"
                      }
                  },
                  {
                      "rulePriority": 3,
                      "description": "Expire all untagged images immediately",
                      "selection": {
                          "tagStatus": "untagged",
                          "countType": "sinceImagePushed",
                          "countUnit": "days",
                          "countNumber": 1
                      },
                      "action": {
                          "type": "expire"
                      }
                  },
                  {
                      "rulePriority": 4,
                      "description": "Keep last 10 `template` images",
                      "selection": {
                          "tagStatus": "tagged",
                          "tagPrefixList": ["template"],
                          "countType": "imageCountMoreThan",
                          "countNumber": 10
                      },
                      "action": {
                          "type": "expire"
                      }
                  },
                  {
                      "rulePriority": 999,
                      "description": "Expire other tagged images after 60 days",
                      "selection": {
                          "tagStatus": "any",
                          "countType": "sinceImagePushed",
                          "countUnit": "days",
                          "countNumber": 60
                      },
                      "action": {
                          "type": "expire"
                      }
                  }
              ]
          }