# Copy built app into nginx container
FROM nginx:1.13.9-alpine
COPY defi-direct-ui/build/. /usr/share/nginx/html
COPY defi-direct-admin-ui/build/. /usr/share/nginx/html/admin

RUN cp /usr/share/nginx/html/default.conf /etc/nginx/conf.d/default.conf
RUN rm /usr/share/nginx/html/default.conf
RUN find /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]