apiVersion: v1
kind: Service
metadata:
  name: defi-direct-api-api-qa
  labels:
    app: defi-direct-api
    tier: api  
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: defi-direct-api
    tier: api
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defi-direct-api-api-qa
  labels:
    app: defi-direct-api
    tier: api
    sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defi-direct-api
      tier: api
  strategy:
    type: RollingUpdate
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: defi-direct-api
        tier: api
        sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}}
    spec:
      initContainers:
      - image: 680054776144.dkr.ecr.us-east-1.amazonaws.com/defi-apps-defidirect:{{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}}.dbmigrator
        name: defi-direct-api-dbmigrator-qa
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "qa"
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: single-request-reopen
      containers:
      - image: 680054776144.dkr.ecr.us-east-1.amazonaws.com/defi-apps-defidirect:{{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}}.api
        name: defi-direct-api-api-qa
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "qa"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        livenessProbe:
          httpGet:
            path: /v1/healthcheck/healthz?key={{HealthCheckOptions.Key}}
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /v1/healthcheck/readiness?key={{HealthCheckOptions.Key}}
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defi-direct-api-api-qa-ext-ingress
  namespace: qa
  labels:
    app: defi-direct-api
    tier: api
  annotations:
    kubernetes.io/ingress.class: nlb
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 25m
spec:
  tls:
  - hosts:
    - api-qa.defidirect.com
    secretName: star-defidirect-com-cert
  rules:
  - host: api-qa.defidirect.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: defi-direct-api-api-qa
            port:
              number: 80