apiVersion: v1
kind: Service
metadata:
  name: defi-directui-{{TEST_ENVIRONMENT_NAME}}
  labels:
    app: defi-directui
    tier: api
    testEnvironmentId: defi-directui-{{TEST_ENVIRONMENT_NAME}} 
    sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}} 
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: defi-directui
    tier: api
    testEnvironmentId: defi-directui-{{TEST_ENVIRONMENT_NAME}} 
    sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}} 
  type: NodePort
           
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defi-directui-{{TEST_ENVIRONMENT_NAME}}
  labels:
    app: defi-directui
    tier: api
    testEnvironmentId: defi-directui-{{TEST_ENVIRONMENT_NAME}}
    sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}} 
spec:
  selector:
    matchLabels:
      app: defi-directui
      tier: api
      sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}}
  strategy:
    type: Recreate
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: defi-directui
        tier: api
        testEnvironmentId: defi-directui-{{TEST_ENVIRONMENT_NAME}}
        sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}} 
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: single-request-reopen
      containers:
      - image: 680054776144.dkr.ecr.us-east-1.amazonaws.com/defi-apps-directui:{{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}}.ui
        name: defi-directui-{{TEST_ENVIRONMENT_NAME}}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "test"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        livenessProbe:
          httpGet:
            path: /v1/healthcheck/healthz?key={{HealthCheckOptions.Key}}
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /v1/healthcheck/readiness?key={{HealthCheckOptions.Key}}
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defi-directui-{{TEST_ENVIRONMENT_NAME}}-ingress
  labels:
    app: defi-directui
    tier: api
    testEnvironmentId: defi-directui-{{TEST_ENVIRONMENT_NAME}} 
    sourceBuildId: {{BRANCH_NAME_LOWERCASE}}-{{BUILD_NUMBER}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "ssl"
    nginx.ingress.kubernetes.io/proxy-body-size: 25m
spec:
  rules:
  - host: services.nonprod.defiapps.com
    http:
      paths:
      - path: /test/directui-{{TEST_ENVIRONMENT_NAME}}
        pathType: Prefix
        backend:
          service:
            name: defi-directui-{{TEST_ENVIRONMENT_NAME}}
            port:
              number: 80